// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SummonerMatch;

#nullable disable

namespace SummonerMatch.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SummonerMatch.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipo"), 1L, 1);

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FkPartida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JugadorAdc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JugadorJungle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JugadorMid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JugadorSupport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JugadorTop")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEquipo");

                    b.ToTable("Equipo");
                });

            modelBuilder.Entity("SummonerMatch.Partida", b =>
                {
                    b.Property<int>("IdPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPartida"), 1L, 1);

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FkTipoPartida")
                        .HasColumnType("int");

                    b.Property<string>("FkTorneo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FkUsuarioCreador")
                        .HasColumnType("int");

                    b.Property<string>("JugadorAdc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JugadorJungle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JugadorMid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JugadorSupport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JugadorTop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPartida");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("SummonerMatch.Posicion", b =>
                {
                    b.Property<int>("IdPosicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPosicion"), 1L, 1);

                    b.Property<string>("NombrePosicion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPosicion");

                    b.ToTable("Posicion");
                });

            modelBuilder.Entity("SummonerMatch.Rango", b =>
                {
                    b.Property<int>("IdRango")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRango"), 1L, 1);

                    b.Property<string>("NombreRango")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRango");

                    b.ToTable("Rango");
                });

            modelBuilder.Entity("SummonerMatch.Region", b =>
                {
                    b.Property<int>("IdRegion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegion"), 1L, 1);

                    b.Property<string>("NombreRegion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRegion");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("SummonerMatch.TipoPartida", b =>
                {
                    b.Property<int>("IdTipoPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoPartida"), 1L, 1);

                    b.Property<string>("NombreTipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoPartida");

                    b.ToTable("TipoPartida");
                });

            modelBuilder.Entity("SummonerMatch.Torneo", b =>
                {
                    b.Property<int>("IdTorneo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTorneo"), 1L, 1);

                    b.Property<int?>("CantidadEquipos")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTorneo");

                    b.ToTable("Torneo");
                });

            modelBuilder.Entity("SummonerMatch.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EsAdministrador")
                        .HasColumnType("bit");

                    b.Property<int?>("FkPosicion")
                        .HasColumnType("int");

                    b.Property<int?>("FkRango")
                        .HasColumnType("int");

                    b.Property<int?>("FkRegion")
                        .HasColumnType("int");

                    b.Property<int?>("FkValoracion")
                        .HasColumnType("int");

                    b.Property<string>("ImagenPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioLoL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SummonerMatch.Valoracion", b =>
                {
                    b.Property<int>("IdValoracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdValoracion"), 1L, 1);

                    b.Property<int?>("CantidadValoraciones")
                        .HasColumnType("int");

                    b.Property<float?>("PuntuacionMedia")
                        .HasColumnType("real");

                    b.HasKey("IdValoracion");

                    b.ToTable("Valoracion");
                });
#pragma warning restore 612, 618
        }
    }
}
